# Generated by Django 3.2.7 on 2021-09-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_auto_20210923_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
